import ClientProductsPage from './ClientProductsPage';

export const metadata = {
  title: 'Products — Sports Barrier Netting & Equipment',
  description:
    'Browse Cereburum Sports\'s full range of sports barrier netting, cricket nets, football nets, and custom netting solutions for sports facilities across Pakistan.',
};

const categories = [
  {
    id: 'crickeet-net-24',
    title: 'Parachute 24',
    subtitle: 'Cricket Netting',
    filterGroup: 'Cricket',
    image: '/images/products/parachute-24.jpg',
    tag: 'Best Seller',
    tagColor: 'sand',
    desc: 'Premium joint-free cotton netting, machine-made for superior durability and fully customizable in size and color to suit sports, animal enclosures, and multi-purpose safety needs.',
    features: ['Joint-free construction', 'Machine-made high-quality', 'Fully customizable size and color', 'Optimized for softball and multi-sport use'],
    specs: [
      { label: 'Material', value: 'Parachute 24' },
      { label: 'Mesh Size', value: '1.75" (45mm)' },
      { label: 'Dimensions', value: '100 ft. x 10 ft.' },
      { label: 'Customizable', value: 'Yes' },
    ],
  },
  {
    id: 'cricket-net-36',
    title: 'Parachute 36',
    subtitle: 'Cricket Netting',
    filterGroup: 'Cricket',
    image: '/images/products/parachute-36.jpg',
    tag: 'Best Seller',
    tagColor: 'sand',
    desc: 'Parachute 36 is an ultra-durable, joint-free netting offering machine-made precision and superior strength for professional sports, safety, and heavy-duty custom needs.',
    features: ['Seamless joint-free design', 'Premium-grade machine-knit mesh', 'Tailor-made dimensions and color palettes', 'Engineered specifically for hardball cricket'],
    specs: [
      { label: 'Material', value: 'Parachute 36' },
      { label: 'Mesh Size', value: '1.75" (45mm)' },
      { label: 'Dimensions', value: '100 ft. x 10 ft.' },
      { label: 'Customizable', value: 'Yes' },
    ],
  },
  {
    id: 'cricket-net-60',
    title: 'Parachute 60',
    subtitle: 'Cricket Netting',
    filterGroup: 'Cricket',
    image: '/images/products/parachute-60.jpg',
    tag: 'Best Seller',
    tagColor: 'sand',
    desc: 'The gold-standard Parachute 60 offers ultimate-strength boundary and goal netting with a heavy-duty, weatherproof build designed for professional stadiums and high-intensity match play.',
    features: ['Industrial-grade reinforced mesh', 'Maximum impact resistance', 'Weatherproof boundary and goal solutions', 'Bespoke sizing for Olympic-standard pitches'],
    specs: [
      { label: 'Material', value: 'Parachute 60' },
      { label: 'Mesh Size', value: '1.75" (45mm)' },
      { label: 'Dimensions', value: '100 ft. x 10 ft.' },
      { label: 'Customizable', value: 'Yes' },
    ],
  },
  {
    id: 'polyester-8',
    title: 'Polyester 8',
    subtitle: 'Cricket Netting',
    filterGroup: 'Cricket',
    image: '/images/products/polyester-8.jpg',
    tag: null,
    tagColor: null,
    desc: 'Polyester 8 is a premium, stretch-enhanced netting featuring a high-elasticity knit for superior flexibility and vibrant, fine-tuned color shades across professional sports and custom installations.',
    features: ['High-stretch elastic composition', 'Seamless joint-free precision', 'Rich, multi-tonal color finishes', 'Dynamic impact absorption for high-performance sports'],
    specs: [
      { label: 'Material', value: 'Polyester 8' },
      { label: 'Mesh Size', value: '1.75" (45mm)' },
      { label: 'Dimensions', value: '100 ft. x 10 ft.' },
      { label: 'Customizable', value: 'Yes' },
    ],
  },
  {
    id: 'polyester-12',
    title: 'Polyester 12',
    subtitle: 'Cricket Netting',
    filterGroup: 'Cricket',
    image: '/images/products/polyester-12.jpg',
    tag: null,
    tagColor: null,
    desc: 'The advanced Polyester 12 is a reinforced, high-tenacity netting that combines superior tensile strength with elastic precision, delivering a heavy-duty, joint-free solution for professional-grade sports environments.',
    features: ['Enhanced high-density elastic weave', 'Industrial-strength joint-free construction', 'Superior color retention and vibrant shading', 'Optimized shock absorption for hardball cricket'],
    specs: [
      { label: 'Material', value: 'Polyester 12' },
      { label: 'Mesh Size', value: '1.75" (45mm)' },
      { label: 'Dimensions', value: '100 ft. x 10 ft.' },
      { label: 'Customizable', value: 'Yes' },
    ],
  },
  {
    id: 'polyester-double-layer',
    title: 'Polyester DL',
    subtitle: 'Cricket Netting',
    filterGroup: 'Cricket',
    image: '/images/products/polyester-dl.jpg',
    tag: null,
    tagColor: null,
    desc: 'The Polyester Double Layer features a dual-reinforced weave for maximum density, offering heavy-duty impact resistance and superior shock absorption for high-velocity sports and professional enclosures.',
    features: ['High-density dual-layered architecture', 'Maximum impact for high-velocity play', 'Reinforced elastic-enhanced weave', 'Industrial-strength joint-free construction'],
    specs: [
      { label: 'Material', value: 'Polyester Double Layer' },
      { label: 'Mesh Size', value: '1.75" (45mm)' },
      { label: 'Dimensions', value: '100 ft. x 10 ft.' },
      { label: 'Customizable', value: 'Yes' },
    ],
  },
  {
    id: 'cotton-net',
    title: 'Cotton Net',
    subtitle: 'Cricket Netting',
    filterGroup: 'Cricket',
    image: '/images/products/cotton.jpg',
    tag: null,
    tagColor: null,
    desc: 'Our essential Cotton Net provides a lightweight and versatile solution for casual sports and avian enclosures, offering a cost-effective, machine-made netting for low-impact environments.',
    features: ['Lightweight machine-made cotton knit', 'Soft-texture finish for animal safety', 'Ideal for bird-proofing and garden protection', 'Budget-friendly multipurpose netting'],
    specs: [
      { label: 'Material', value: 'Cotton Net' },
      { label: 'Mesh Size', value: '1.75" (45mm)' },
      { label: 'Dimensions', value: '100 ft. x 10 ft.' },
      { label: 'Customizable', value: 'Yes' },
    ],
  },
  {
    id: 'crickeet-net-12',
    title: 'Parachute 12',
    subtitle: 'Cricket Netting',
    filterGroup: 'Cricket',
    image: '/images/products/parachute-12.jpg',
    tag: null,
    tagColor: null,
    desc: 'Parachute 12 is a reliable, mid-tier netting that bridges the gap between casual cotton and professional-grade mesh, offering enhanced durability and weather resistance for everyday sports and protection.',
    features: ['Upgraded synthetic strength', 'Seamless machine-made precision', 'Versatile use for sports and light enclosures', 'Cost-effective performance upgrade from cotton'],
    specs: [
      { label: 'Material', value: 'Parachute 12' },
      { label: 'Mesh Size', value: '1.75" (45mm)' },
      { label: 'Dimensions', value: '100 ft. x 10 ft.' },
      { label: 'Customizable', value: 'Yes' },
    ],
  },
  {
    id: 'nylon-105',
    title: 'Nylon 105',
    subtitle: 'Football Goal',
    filterGroup: 'Football',
    image: '/images/products/nylon-105.jpg',
    tag: null,
    tagColor: null,
    desc: 'The Nylon 105 is our foundational football goal netting, featuring traditional handmade craftsmanship and a high-tensile build available in a variety of vibrant colors to match your team or club.',
    features: ['Traditional handmade knotted construction', 'Resilient Nylon 105 grade material', 'Available in a wide range of custom colors', 'Weather-resistant finish for outdoor play'],
    specs: [
      { label: 'Material', value: 'Nylon' },
      { label: 'Mesh Size', value: '3"' },
      { label: 'Dimensions', value: 'Standard Goal' },
      { label: 'Customizable', value: 'Yes' },
    ],
  },
  {
    id: 'nylon-106',
    title: 'Nylon 106',
    subtitle: 'Football Goal',
    filterGroup: 'Football',
    image: '/images/products/nylon-106.jpg',
    tag: 'Best Seller',
    tagColor: 'sand',
    desc: 'The Nylon 106 is a high-performance football goal net offering increased thickness and superior tensile strength over standard grades, handcrafted for enhanced durability in competitive environments.',
    features: ['Premium heavy-duty handmade knotting', 'Upgraded Nylon 106 high-density twine', 'Enhanced tear resistance for powerful shots', 'Vibrant color customization options', 'Long-lasting performance in all weather conditions'],
    specs: [
      { label: 'Material', value: 'Nylon' },
      { label: 'Mesh Size', value: '3"' },
      { label: 'Dimensions', value: 'Standard Goal' },
      { label: 'Customizable', value: 'Yes' },
    ],
  },
  {
    id: 'nylon-107',
    title: 'Nylon 107',
    subtitle: 'Football Goal',
    filterGroup: 'Football',
    image: '/images/products/nylon-107.jpg',
    tag: null,
    tagColor: null,
    desc: 'The Nylon 107 is our elite-tier handcrafted goal net, featuring an extra-thick, high-tenacity build designed to withstand the highest-velocity impacts in professional training and match play.',
    features: ['Industrial-strength handmade knotted weave', 'Reinforced Nylon 107 ultra-thick twine', 'Maximum impact absorption for professional use', 'Premium weather-treated color finishes', 'Superior structural integrity for full-size goals'],
    specs: [
      { label: 'Material', value: 'Nylon' },
      { label: 'Mesh Size', value: '3"' },
      { label: 'Dimensions', value: 'Standard Goal' },
      { label: 'Customizable', value: 'Yes' },
    ],
  },
  {
    id: 'parachute-101',
    title: 'Parachute 101',
    subtitle: 'Football Goal',
    filterGroup: 'Football',
    image: '/images/products/parachute-101.jpg',
    tag: null,
    tagColor: null,
    desc: 'Parachute 101 is a premium-grade football net that outperforms standard nylon, offering a superior strength-to-weight ratio and a classic professional aesthetic in its natural white finish.',
    features: ['High-tenacity synthetic parachute fibers', 'Superior tensile strength compared to nylon', 'Classic professional natural white finish', 'Machine-made for consistent mesh tension'],
    specs: [
      { label: 'Material', value: 'Parachute' },
      { label: 'Mesh Size', value: '3"' },
      { label: 'Dimensions', value: 'Standard Goal' },
      { label: 'Customizable', value: 'Yes' },
    ],
  },
  {
    id: 'parachute-104',
    title: 'Parachute 104',
    subtitle: 'Football Goal',
    filterGroup: 'Football',
    image: '/images/products/parachute-104.jpg',
    tag: 'Best Seller',
    tagColor: 'sand',
    desc: 'The Parachute 104 is an ultra-heavy-duty professional goal net, engineered with high-density fibers to provide elite-level durability and impact resistance that surpasses standard competition netting.',
    features: ['High-tenacity synthetic parachute fibers', 'Superior tensile strength compared to nylon', 'Classic professional natural white finish', 'Machine-made for consistent mesh tension'],
    specs: [
      { label: 'Material', value: 'Parachute' },
      { label: 'Mesh Size', value: '3"' },
      { label: 'Dimensions', value: 'Standard Goal' },
      { label: 'Customizable', value: 'Yes' },
    ],
  },
  {
    id: 'polypropylene-102',
    title: 'Polypropylene 102',
    subtitle: 'Football Goal',
    filterGroup: 'Football',
    image: '/images/products/pp-102.jpg',
    tag: null,
    tagColor: null,
    desc: 'The Polypropylene 102 represents the pinnacle of goal net technology, featuring a high-elasticity weave that offers unrivaled impact absorption and superior strength in a clean, professional natural white.',
    features: ['Advanced high-stretch Polypropylene architecture', 'Ultimate impact dampening and shock recovery', 'Superior tensile strength surpassing all standard grades', 'Lightweight yet ultra-durable weather-proof build'],
    specs: [
      { label: 'Material', value: 'Polypropylene' },
      { label: 'Mesh Size', value: '3"' },
      { label: 'Dimensions', value: 'Standard Goal' },
      { label: 'Customizable', value: 'Yes' },
    ],
  },
  {
    id: 'custom',
    title: 'Custom Solutions',
    subtitle: 'Bespoke & Tailored',
    filterGroup: 'Custom',
    image: null,
    tag: 'Tailored',
    tagColor: 'sand',
    desc: 'Got a unique project? We design, manufacture, and install bespoke netting systems for complex architectural spaces, non-standard dimensions, and special requirements.',
    features: ['Full custom design service', 'CAD drawings provided', 'Any dimension or shape', 'Specialized materials', 'Project management included'],
    specs: [
      { label: 'Min. Lead Time', value: '5 business days' },
      { label: 'Design', value: 'CAD-assisted' },
      { label: 'Materials', value: 'Any grade available' },
      { label: 'Dimensions', value: 'No limit' },
    ],
  },
];

export default function ProductsPage() {
  return <ClientProductsPage categories={categories} />;
}
